### ISSUE TITLE
[1장] 자바스크립트는 싱글 스레드 언어인데 어떻게 비동기로 API 데이터 처리가 가능한가요?

### ISSUE THREAD

**Issue by jinsupark4255** [React-DeepDive/DeepDive#12]
📝 p.70 - 79

🧐 자바스크립트는 싱글 스레드 언어이지만, 비동기적으로 API 데이터를 처리할 수 있습니다. 그 방법에 대해서 '이벤트 루프'와 '태스크 큐'를 함께 사용하여 서술해주세요.

**Comment by jinsupark4255** [comment]
## 답안
- 자바스크립트는 이벤트 루프와 태스크 큐를 활용하여 비동기적인 작업을 효율적으로 처리할 수 있습니다.

### 이벤트 루프
- 이벤트 루프는 자바스크립트 엔진 외부에서 실행되며, 프로그램이 종료될 때까지 계속해서 실행됩니다. 주된 기능은 콜 스택이 비어 있을 때 태스크 큐에서 대기 중인 태스크(콜백 함수)를 콜 스택으로 이동시켜 실행하는 것입니다. 이 과정을 통해 비동기 작업의 결과를 처리할 수 있습니다.

### 태스크 큐
- 태스크 큐(또는 이벤트 큐)는 외부 API로부터의 이벤트나, 타이머, HTTP 요청 등과 같은 비동기 작업들의 결과(콜백 함수)를 순차적으로 보관하는 대기열입니다. 여러 개의 태스크 큐가 존재할 수 있으며, 각 큐는 특정 유형의 이벤트를 처리합니다.

### 작동 원리
1. 비동기 함수 실행: 자바스크립트 코드에서 setTimeout, setInterval, fetch 등의 비동기 함수를 호출하면, 자바스크립트 엔진은 해당 호출을 네트워크, 파일 시스템, 타이머 등에 위임합니다.
2. 콜 스택: 자바스크립트 엔진의 콜 스택에는 현재 실행 중인 모든 함수의 호출 정보가 저장됩니다. 콜 스택이 비어 있어야만 새로운 태스크를 수행할 수 있습니다.
3. 이벤트 처리: 비동기 작업이 완료되면, 완료된 작업의 콜백 함수가 태스크 큐에 추가됩니다. 이벤트 루프는 콜 스택이 비어 있을 때 태스크 큐에서 콜백 함수를 콜 스택으로 이동시키고 실행합니다.
4. 콜백 실행: 콜 스택으로 이동된 콜백 함수가 실행되며, 작업 결과를 처리합니다.

**Comment by realzu** [comment]
싱글 스레드이지만, 비동기 작업은 또 다른 스레드에서 진행됩니다.

비동기 함수가 실행이 되면, 콜 스택에 들어가고
web api 에서 작업을 처리하며 (fetch..)
Task queue 에 들어갔다가 call stack이 비었을 때 비동기 함수의 콜백 함수가 이동되어 실행합니다.

**Comment by wathertheqlant** [comment]
자바스크립트는 싱글 스레드 방식으로 동작하기 때문에, 
여러 작업을 비동기적으로 병렬적으로 처리 하기 위해서 v8엔진의 이벤트 루프가 이 작업을 가능하도록 도와주는데요.

이벤트 루프가 계속 콜스택과 태스크 큐를 확인하면서, 다음 수행할 작업이 있는지 확인합니다. 
콜스택에 담긴 컨텍스트가 실행되고, 콜스택이 비면 이벤트 루프가 태스크 큐에 대기중인 함수를 우선순위에 따라 콜스택으로 이동시켜 줍니다.
