### ISSUE TITLE
[1장] reduce 메서드에서 초깃값이 없을 때 어떻게 작동할까요?

### ISSUE THREAD

**Issue by realzu** [React-DeepDive/DeepDive#13]
📝 p94-95

🧐 자바스크립트의 reduce 메서드에서 초깃값을 정의하지 않았을 때, 어떻게 작동할까요?

아래의 문제를 기준으로 답변도 함께 작성해주세요!

```javascript
const numbers = [1, 2, 3, 4];

const result = numbers.reduce((acc, curr) => acc + curr);
console.log(result);
```

**Comment by realzu** [comment]
배열의 첫번째 요소가 accumulator 되면서 초깃값이 됩니다.
실질적으로 2번째 요소부터 실행이 되며

1+2
3+3
6+4

결과는 10 이 나옵니다.

**Comment by jinsupark4255** [comment]
배열의 첫번째 요소가 초기값으로 설정되며 reduce의 콜백 함수는 두번째 요소부터 순차적으로 진행됩니다.

**Comment by wathertheqlant** [comment]
배열의 첫번째 값을 시작으로 accumulator 값에 할당되어 연산 됩니다.
result : 10
