### ISSUE TITLE
[1장] truthy와 falsy

### ISSUE THREAD

**Issue by jinsupark4255** [React-DeepDive/DeepDive#3]
📝 p.22 - 23

🧐 문제 상황

소셜 미디어 애플리케이션에 사용될 사용자의 친구 목록을 가져오는 기능을 개발한다고 가정하겠습니다. 
프론트엔드는 백엔드 서버에서 API를 통해 사용자의 친구 목록을 JSON 형태로 받아와 화면에 표시합니다. 
만약, 사용자가 친구를 아직 추가하지 않았다면, API는 빈 배열 []을 반환합니다. 
또한, 사용자 정보를 불러올 때 문제가 발생하면 빈 객체 {}를 반환할 수도 있습니다.

```tsx
function fetchFriends() {
  return fetch('/api/user/friends')
    .then(response => response.json())
    .then(data => {
      if (data) {
        console.log("친구 목록:", data);
        renderFriends(data);
      } else {
        console.log("친구가 없습니다.");
      }
    })
    .catch(error => {
      console.error("API 호출에 실패했습니다.", error);
    });
}

function renderFriends(friends) {
  if (friends.length > 0) {
    friends.forEach(friend => {
      console.log(friend.name);
    });
  } else {
    console.log("친구 목록이 비어있습니다.");
  }
}

```
위의 코드에서 발생할 수 있는 문제가 무엇인지, truthy와 falsy를 활용하여 설명 부탁드립니다.

**Comment by Whoknow77** [comment]
빈배열도 `truthy`로 판단하므로 친구목록에 서버에서 받아오는 `data`가 빈 배열임에도 친구가 있을때만 실행되어야 하는 `renderFriends`함수가 호출되어 문제가 발생할 수 있습니다.

**Comment by dlantjdgkgk** [comment]
JavaScript에서 빈 배열 []은 truthy입니다. 이 경우 if (data)는 true가 되어 renderFriends(data)가 호출됩니다.

**Comment by realzu** [comment]
[]와 {}는 모두 truthy한 값이라, "친구가 없습니다" 라는 Console.log 문은 호출 가능성이 없습니다.
또한 renderFriends 에서 {} 값이 인자로 들어왔을 때, length 호출시 에러가 발생합니다
