### ISSUE TITLE
[1장] 함수 표현식과 선언문의 차이

### ISSUE THREAD

**Issue by realzu** [React-DeepDive/DeepDive#8]
📝 p.37 ~ 39

🧐 문제 내용

호이스팅의 관점에서 함수 표현식과 선언문의 차이를 설명해주세요!

**Comment by Whoknow77** [comment]
선언식은 함수 호이스팅에 의해서 런타임 이전에 평가가 돼서 선언 순서에 상관없이 어디서든 호출할 수 있다.
표현식은 변수 호이스팅에 의해서 런타임 이전에 `undefined`로 평가 돼서 선언 이전에는 사용을 못한다.

**Comment by Whoknow77** [comment]
> @Whoknow77 이 말씀해 주신 호이스팅 부분에 의견에 덧붙여
> 
> 선언문은 일반문 무언가 값을 산출하지 않는 구문 표현식은 무언가 값을 산출하는 구문 이라는 차이가 있다 생각되어요

감사합니다! 선언문을 선언식이라고 말해버렸네요..

**Comment by realzu** [comment]
오 제가 선언문을 선언식이라고 썼군요.. 감사합니다!
